### PR TITLE
Fix journey line over idl not connecting all point issue

### PR DESCRIPTION
**Pull request by MufengNiu**
relared to issue https://github.com/HughCraig/GHAP/issues/330 , https://github.com/HughCraig/GHAP/issues/329 , 
#11

### CODE REVIEW

**Review by yangli0516 — CHANGES_REQUESTED** [review]
Please change all instances of `var` to `const` or `let` for the consistency.

**Comment by MufengNiu** [comment]
> Please change all instances of `var` to `const` or `let` for the consistency.

Updated

**Comment by yangli0516** [comment]
> > Please change all instances of `var` to `const` or `let` for the consistency.
> 
> Updated

There're still a couple of places in the code using `var`. Please have another review.

**Comment by MufengNiu** [comment]
> > > Please change all instances of `var` to `const` or `let` for the consistency.
> > 
> > 
> > Updated
> 
> There're still a couple of places in the code using `var`. Please have another review.

Have change all occurrences of 'var' to 'let'

**Comment by yangli0516** [comment]
> > > > Please change all instances of `var` to `const` or `let` for the consistency.
> > > 
> > > 
> > > Updated
> > 
> > 
> > There're still a couple of places in the code using `var`. Please have another review.
> 
> Have change all occurrences of 'var' to 'let'

@MufengNiu, I can see you have fixed the `var` statements in all files, which is a good thing to do to keep our code consistent. However, a better practice is to use `const` instead of `let` when possible if the variable is not going to be changed. This will prevent potential problems down the development track.

I know this is not related to this issue. But based on the fact that we have gone this far, we want to get things right using this opportunity. Would you mind having another pass through to use `const` when it fits?

**Comment by MufengNiu** [comment]
> > > > > Please change all instances of `var` to `const` or `let` for the consistency.
> > > > 
> > > > 
> > > > Updated
> > > 
> > > 
> > > There're still a couple of places in the code using `var`. Please have another review.
> > 
> > 
> > Have change all occurrences of 'var' to 'let'
> 
> @MufengNiu, I can see you have fixed the `var` statements in all files, which is a good thing to do to keep our code consistent. However, a better practice is to use `const` instead of `let` when possible if the variable is not going to be changed. This will prevent potential problems down the development track.
> 
> I know this is not related to this issue. But based on the fact that we have gone this far, we want to get things right using this opportunity. Would you mind having another pass through to use `const` when it fits?

Hi @yangli0516 , Thanks for reminding, i have replaced 'let' and 'var' with 'const' for immutable variables

**Review by yangli0516 — APPROVED** [review]

**Pull request merged**
