### PR TITLE
add config support for cluster font color

### PR DESCRIPTION
**Pull request by MufengNiu**
Add config support for cluster font color

### CODE REVIEW

**Comment by MufengNiu** [comment]
"clusterFontColor" controls the font colour of clusters in the cluster map. The default color is '#004a5d' (dark blue). 
it should be added to "display" as a global setting.

**Review by yangli0516 — COMMENTED** [review]
Does this configuration also work with the collection-cluster view?

**Comment by MufengNiu** [comment]
> Does this configuration also work with the collection-cluster view?

for this config, should we make it a global setting for all datasets or do we load individual settings for each dataset?

**Comment by yangli0516** [comment]
> > Does this configuration also work with the collection-cluster view?
> 
> for this config, should we make it a global setting for all datasets or do we load individual settings for each dataset?


For now, leave the setting at the dataset level. When a dataset is viewed in the cluster collection view, apply the font color if the GeoJSON of the dataset has the `clusterFontColor` setting.

**Comment by MufengNiu** [comment]
> > > Does this configuration also work with the collection-cluster view?
> > 
> > 
> > for this config, should we make it a global setting for all datasets or do we load individual settings for each dataset?
> 
> For now, leave the setting at the dataset level. When a dataset is viewed in the cluster collection view, apply the font color if the GeoJSON of the dataset has the `clusterFontColor` setting.

Added. 'clusterFontColor ' setting on each dataset will take effect now in the collection-cluster map.

**Comment by yangli0516** [comment]
@MufengNiu have sync the change to the test site.

**Pull request merged**
